name: 'API-Tests'

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  host-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v3

      - name: "Checking invalid host header"
        env: 
          USERNAME: ${{ secrets.WEBUI_TESTING_LOGIN }} 
          PASSWORD: ${{ secrets.WEBUI_TESTING_PASS }}
        run: python3 tests/autotest1.py 

