---

name: 'API-Tests'
on:
  push:
    branches:
      - "greggid/ci-cd-tests"

jobs:
  host-test:
    runs-on: ubuntu-latest
    steps:
      - name: clone rep
      - uses: actions/checkout@v3
      - name: Statrt autotest
          run: |python3
            ../../tests/autotest1.py

